AWSTemplateFormatVersion: '2010-09-09'
Description: DeploymentBucket
Parameters:
  BucketName:
    Type: String
    Description: Deployment bucket name
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::AccountId}-template-${AWS::Region}-s3-deployment-bucket'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Value: !Ref Bucket
