name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ms-aws-store-products

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js v20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
        env:
          MONGO_PW: ${{ secrets.MONGO_PW }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONG_DB_NAME: ${{ secrets.MONG_DB_NAME }}

      - name: Install dependencies
        run: npm install
        working-directory: ms-aws-store-products

      - name: Run all commands
        run: npm run all && cd dist/ && ls -l
        working-directory: ms-aws-store-products
        env:
          MONGO_PW: ${{ secrets.MONGO_PW }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONG_DB_NAME: ${{ secrets.MONG_DB_NAME }}

      - name: Deploy to AWS Lambda
        uses: kazimanzurrashid/aws-lambda-update-action@v2.0.3
        with:
          zip-file: "./dist/lambda.zip"
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"
          lambda-name: "ms-get-products"
