name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master
   

defaults:
  run:
    working-directory: ms-aws-store-products

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js v20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"
          function-name: "ms-get-products"
          zip-file: "./dist/lambda.zip"

      - name: Install dependencies
        run: npm install
        working-directory: ms-aws-store-products

      - name: 'Create env file'
        run: |
          echo "MONGO_PW=${{ vars.MONGO_PW }}" >> .env
          echo "MONGO_USERNAME=${{ vars.MONGO_USERNAME }}" >> .env
          echo "MONG_DB_NAME=${{ vars.MONG_DB_NAME }}" >> .env
          

      - name: Run all commands
        run: npm run all
        working-directory: ms-aws-store-products

